// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// GetNllDelta
double GetNllDelta(const NumericVector& delta, const NumericMatrix& matX, const Eigen::Map<Eigen::MatrixXd>& matY, const Eigen::Map<Eigen::MatrixXd>& matH);
RcppExport SEXP MUCM_GetNllDelta(SEXP deltaSEXP, SEXP matXSEXP, SEXP matYSEXP, SEXP matHSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type matX(matXSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type matY(matYSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type matH(matHSEXP);
    rcpp_result_gen = Rcpp::wrap(GetNllDelta(delta, matX, matY, matH));
    return rcpp_result_gen;
END_RCPP
}
