#' @title emPlot1D
#' @description Plot emulator distribution across a single input
#' @param fit  Object of class \code{emulatorFit} generated by \code{\link{fitEmulator}} or \code{\link{fitEmulatorData}}
#' @param input The default is set to 1
#' @param lower The default is set to Null
#' @param upper The default is set to Null
#' @param alpha The default is set to 0.05
#' @author Jeremy Oakley.
#' @return Returns a plot of a single input against output
#' @note This function requires R package \pkg{ggplot2} to be installed.
#' @export
emPlot1D <- function(fit, input = 1, lower = NULL, upper = NULL, alpha = 0.05) {
    if (!requireNamespace("ggplot2", quietly = TRUE))
        stop("this function requires R package ggplot2 to be installed")
    
    # ensure new and old fits are backward compatible
    fit <- updateFit(fit)
    
    if (is.null(lower)) 
        lower <- min(fit$training.inputs[, input, drop = FALSE])
    if (is.null(upper)) 
        upper <- max(fit$training.inputs[, input, drop = FALSE])
    
    newinputs <- matrix(apply(fit$training.inputs, 2, mean), 
                    nrow = 100, ncol = ncol(fit$training.inputs), byrow = T)
    newinputs[, input] <- seq(from = lower, to = upper, length = 100)
    colnames(newinputs) <- colnames(fit$training.inputs)
    
    predictions <- predict(fit, newinputs)
    df1 <- data.frame(x = fit$training.inputs[, input], y = fit$training.outputs[,1])
    df2 <- data.frame(x = newinputs[, input], m = predictions$posterior.mean[, 1])
    
    if (!is.null(predictions$posterior.variance)) {
        df2$s <- diag(predictions$posterior.variance) ^ 0.5
    } else if (!is.null(predictions$standard.deviation)) {
        df2$s <- predictions$standard.deviation
    }
    
    p <- ggplot2::ggplot(df1)
    p + ggplot2::geom_point(ggplot2::aes(x = x, y = y)) + 
        ggplot2::geom_line(data = df2, ggplot2::aes(x = x, y = m), col = "red") + 
        ggplot2::geom_ribbon(data = df2, ggplot2::aes(x = x, ymax = m + 2 * s, ymin = m - 2 * s),
                             fill = "red", alpha = I(0.5))
} 
