# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param delta [q] is a vector the log of the correlation length
#' @param matX [p x q] is the input data matrix with p observations and q variables
#' @param matH [q x ?] is the H matrix, the number of columns depends on the prior model for the mean function
#' @param matY [p x r] is the output data matrix with p observations and r variables
NULL

#' @export
GetNllDelta <- function(delta, matX, matY, matH) {
    .Call('MUCM_GetNllDelta', PACKAGE = 'MUCM', delta, matX, matY, matH)
}

